CREATE TABLE tbj_usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(11) NOT NULL UNIQUE,
    telefone VARCHAR2(15),
    email VARCHAR2(100),
    marca VARCHAR2(50),
    modelo VARCHAR2(50),
    ano NUMBER(4),
    placa VARCHAR2(10),
    descricao VARCHAR2(255),
    logradouro VARCHAR2(100),
    numero VARCHAR2(10),
    complemento VARCHAR2(50),
    bairro VARCHAR2(50),
    cidade VARCHAR2(50),
    estado VARCHAR2(2),
    cep VARCHAR2(10)
);
